site_name: C2 Language Documentation
repo_url: https://github.com/c2lang
theme: readthedocs
pages:
- Introduction:
  - Philosophy: index.md
  - introduction/evolution.md
  - Hello World: introduction/helloworld.md
  - introduction/code_fragments.md
  - introduction/changes_from_c.md
- Getting Started:
  - getting_started/installation.md
  - getting_started/my_first_project.md
- C2 Language:
  - language/basics.md
  - language/basic_types.md
  - User-defined types: language/user_types.md
  - language/variables.md
  - language/functions.md
  - language/modules.md
  - language/attributes.md
  - language/bitoffsets.md
- Build system:
  - build_system/intro.md
  - Export Control: build_system/symbols.md
  - C2 Module: build_system/c2module.md
- Development:
  - development/contributing.md
  - development/internals.md
  - development/automated_tests.md
  - development/current_status.md
  - development/change_log.md
